"use client";

import React from "react";
import { api } from "@/trpc/react";
import { Book, Code, ExternalLink, User as UserIcon, Calendar, ArrowRight, Users as UsersIcon } from "lucide-react";
import Link from "next/link";
import { format } from "date-fns";
import { exportDocAsMarkdown } from "@/lib/services/doc-export";

export default function CommunityPage() {
  const { data: docs, isLoading } = api.project.getAllDocs.useQuery();

  const handleDownload = (doc: any) => {
    exportDocAsMarkdown({
      id: doc.id,
      type: doc.type as any,
      body: doc.body,
      createdAt: doc.createdAt instanceof Date ? doc.createdAt.toISOString() : new Date(doc.createdAt).toISOString(),
      updatedAt: doc.createdAt instanceof Date ? doc.createdAt.toISOString() : new Date(doc.createdAt).toISOString(),
    });
  };

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="bg-white border-b border-gray-200 pt-10 pb-16">
        <div className="container mx-auto px-4 max-w-7xl text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-50 text-[#fa5028] text-sm font-medium mb-6 border border-orange-100">
            <UsersIcon className="w-4 h-4" />
            <span>Community Gallery</span>
          </div>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-gray-900 mb-6">
            Explore <span className="text-[#fa5028]">Community</span> Knowledge
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
            Discover technical documentations and API references generated by developers worldwide. 
            Learn from architectural patterns and integration guides.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <main className="container mx-auto px-4 max-w-7xl py-12 bg-white">
        {isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm animate-pulse space-y-4">
                <div className="h-6 w-1/3 bg-gray-100 rounded-lg"></div>
                <div className="h-20 w-full bg-gray-50 rounded-xl"></div>
                <div className="h-10 w-full bg-gray-100 rounded-full"></div>
              </div>
            ))}
          </div>
        ) : docs && docs.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {docs.map((doc) => (
              <div 
                key={doc.id} 
                className="group bg-white rounded-3xl border border-gray-100 shadow-sm hover:shadow-xl hover:shadow-[#fa5028]/5 transition-all duration-300 flex flex-col h-full overflow-hidden"
              >
                <div className="p-6 flex-grow flex flex-col">
                  {/* Badge & Type */}
                  <div className="flex items-center justify-between mb-4">
                    <span className={` py-1 rounded-full text-xs font-semibold flex items-center gap-1.5 ${
                      doc.type === 'API' ? ' text-orange-600' : ' text-orange-600'
                    }`}>
                      {doc.type} REFERENCE
                    </span>
                    <span className="text-gray-400 text-xs flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {format(new Date(doc.createdAt), 'MMM dd, yyyy')}
                    </span>
                  </div>

                  {/* Title & Project */}
                  <div className="space-y-2 mb-6">
                    <h3 className="text-xl font-bold text-gray-900 line-clamp-1  transition-colors">
                      {doc.projectData.repoisteryUrl?.split('/').pop() || 'Untitled Project'}
                    </h3>
                    <div className="flex items-center gap-2 text-sm text-gray-500">
                      <div className="w-6 h-6 rounded-full bg-gray-100 flex items-center justify-center overflow-hidden">
                        {doc.projectData.user.image ? (
                          <img src={doc.projectData.user.image} alt={doc.projectData.user.name || ''} className="w-full h-full object-cover" />
                        ) : (
                          <UserIcon className="w-3 h-3 text-gray-400" />
                        )}
                      </div>
                      <span className="font-medium truncate">{doc.projectData.user.name || 'Anonymous User'}</span>
                    </div>
                  </div>

                  {/* Body Preview */}
                  <div className="flex-grow">
                    <p className="text-gray-500 text-sm line-clamp-3 leading-relaxed mb-4">
                      {typeof doc.body === 'string' 
                        ? JSON.parse(doc.body).overview || JSON.parse(doc.body).description || "Check out this documentation for comprehensive code insights and architectural details."
                        : (doc.body as any).overview || (doc.body as any).description || "Check out this documentation for comprehensive code insights and architectural details."
                      }
                    </p>
                  </div>

                  {/* Actions */}
                  <div className="pt-6 mt-auto">
                    <button 
                      onClick={() => handleDownload(doc)}
                      className="inline-flex items-center justify-center w-full gap-2 px-6 py-3 bg-gray-100 text-gray-900 rounded-2xl font-semibold hover:bg-[#fa5028] hover:text-white transition-colors cursor-pointer group/btn"
                    >
                      View Documentation
                      <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-1 transition-transform" />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="text-center py-20 bg-white rounded-3xl border-2 border-dashed border-gray-100">
            <div className="max-w-xs mx-auto space-y-4">
              <div className="p-4 bg-gray-50 rounded-full w-16 h-16 mx-auto flex items-center justify-center">
                <Book className="w-8 h-8 text-gray-300" />
              </div>
              <h3 className="text-lg font-bold text-gray-900">No documentations yet</h3>
              <p className="text-gray-500">Be the first one to share your project with the community!</p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

function Users(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  );
}
